export const mockTableData = [
  {
    id: 144,
    name: '内部数据',
    read: true,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 145,
        name: '内部数据监控',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 144,
        children: null,
      },
    ],
  },
  {
    id: 146,
    name: '泰康养老自选池',
    read: true,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 147,
        name: '自选关注股',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 146,
        children: null,
      },
    ],
  },
  {
    id: 148,
    name: '投资池（定制功能）',
    read: true,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 149,
        name: '股票池',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 148,
        children: null,
      },
    ],
  },
  {
    id: 150,
    name: '研究成果',
    read: false,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 151,
        name: '内部研究',
        read: false,
        editLabelName: '',
        isParent: false,
        parentId: 150,
        children: null,
      },
    ],
  },
  {
    id: 152,
    name: '工作管理',
    read: false,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 154,
        name: '晨会中心',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 152,
        children: null,
      },
      {
        id: 153,
        name: '日程管理',
        read: false,
        editLabelName: '',
        isParent: false,
        parentId: 152,
        children: null,
      },
    ],
  },
  {
    id: 155,
    name: '系统管理',
    read: true,
    editLabelName: '',
    isParent: true,
    parentId: null,
    children: [
      {
        id: 158,
        name: '权限管理',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 155,
        children: null,
      },
      {
        id: 157,
        name: '角色管理',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 155,
        children: null,
      },
      {
        id: 156,
        name: '用户管理',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 155,
        children: null,
      },
      {
        id: 159,
        name: '工作流管理',
        read: true,
        editLabelName: '',
        isParent: false,
        parentId: 155,
        children: null,
      },
    ],
  },
];

export const pageIdAuthMap = {
  read_145_144: 'ROBOAMS_MONITOR_GROUP_MY',
  read_147_146: 'ROBOAMS_SECURITY_POOL_PRIVATE',
  read_149_148: 'ROBOAMS_SECURITY_POOL_PUBLIC',
  read_151_150: 'ROBOAMS_INTERNAL_RESEARCH_PrivateClouds',
  read_154_152: 'ROBOAMS_MORNING_MEETING',
  read_153_152: 'ROBOAMS_SCHEDULE_MANAGEMENT',
  read_158_155: 'ROBOAMS_PRIVILEGE_MGMT',
  read_157_155: 'ROBOAMS_ROLE_MGMT',
  read_156_155: 'ROBOAMS_USER_MGMT',
  read_159_155: 'ROBOAMS_WORKFLOW_MGMT',
};
